config/routes.rb
Ilbdmt::Application.routes.draw do
  resources :catalogs

  resources :users
	
	resources :sessions, only: [:new, :create, :destroy]

	resources :areas

  resources :activities

  get "sell_tickets/home"
  
	resources :pools

  resources :games

  resources :matches

	root to: 'static_pages#home'
	match '/signup/', to: 'users#new',						via: 'get'
	match '/signin/', to: 'sessions#new',					via: 'get'
	match '/signout/',to: 'sessions#destroy',			via: 'delete'
	match '/help',		to: 'static_pages#help',		via: 'get'
	match '/about',		to: 'static_pages#about',		via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

	match '/sell',			to: 'sell_tickets#home',	via: 'get'
	match '/game',			to: 'sell_tickets#game',	via: 'get'
	match '/score',			to: 'sell_tickets#score',	via: 'get'
	match '/total',			to: 'sell_tickets#total',	via: 'get'
	match '/hfad',			to: 'sell_tickets#hfad',	via: 'get'

	match '/badminton',	to: 'activities#badminton',	via: 'get'
	match '/skiing',	to: 'activities#skiing',	via: 'get'

end

app/models/pool.rb
class Pool < ActiveRecord::Base
	belongs_to :game
	belongs_to :match
end

app/controllers/pools_controller.rb
class PoolsController < ApplicationController
	before_action :set_pool, only: [:show, :edit, :update, :destroy]

  # GET /pools
  # GET /pools.json
  def index
    @pools = Pool.all
  end

  # GET /pools/1
  # GET /pools/1.json
  def show
  end

  # GET /pools/new
  def new
    @pool = Pool.new
  end

  # GET /pools/1/edit
  def edit
  end

  # POST /pools
  # POST /pools.json
  def create
    @pool = Pool.new(pool_params)
		@pool.create_time = Time.now
    respond_to do |format|
      if @pool.save
        format.html { redirect_to @pool, notice: '奖池创建成功.' }
        format.json { render action: 'show', status: :created, location: @pool }
      else
        format.html { render action: 'new' }
        format.json { render json: @pool.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pools/1
  # PATCH/PUT /pools/1.json
  def update
    respond_to do |format|
      if @pool.update(pool_params)
        format.html { redirect_to @pool, notice: 'Pool was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pool.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pools/1
  # DELETE /pools/1.json
  def destroy
    @pool.destroy
    respond_to do |format|
      format.html { redirect_to pools_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pool
      @pool = Pool.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pool_params
      params.require(:pool).permit(:game_id, :match_id, :create_time, :sell_statu, :match_result)
    end
end

app/helpers/pools_helper.rb
module PoolsHelper
end

app/views/pools/_form.html.erb
<%= form_for(@pool) do |f| %>
  <% if @pool.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pool.errors.count, "error") %> prohibited this pool from being saved:</h2>

      <ul>
      <% @pool.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :'选择游戏' %><br>
		<%= f.select(:game_id, options_from_collection_for_select(Game.all, :id, :game_name)) %>
    <%#= f.number_field :game_id %>
  </div>
  <div class="field">
    <%= f.label :'选择赛事' %><br>
		<%= f.select(:match_id, options_from_collection_for_select(Match.all, :id, :match_no)) %>
    <%#= f.text_field :match_id %>
  </div>
  <div class="field">
    <%#= f.label :create_time %><br>
    <%#= f.datetime_select :create_time %>
  </div>
  <div class="field">
    <%= f.label :'销售状态' %><br>
    <%= select_tag(:sell_status, options_for_select([['初始', 0], ['开始销售', 1], ['暂停销售', 2], ['停止销售', 3], ['退款']], 0 )) %>
  </div>
  <div class="field">
    <%= f.label :'赛果' %><br>
    <%= f.number_field :match_result %>
  </div>
  <div class="actions">
    <%= f.submit '提交'%>
  </div>
<% end %>

app/views/pools/edit.html.erb
<h1>修改奖池</h1>

<%= render 'form' %>

<%= link_to '查看', @pool %> |
<%= link_to '返回', pools_path %>

app/views/pools/index.html.erb
<h1>奖池列表</h1>

<table>
  <thead>
    <tr>
      <th>游戏名称</th>
      <th>赛事编号</th>
      <th>创建时间</th>
      <th>奖池状态</th>
      <th>赛果</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @pools.each do |pool| %>
      <tr>
        <td><%= Game.find(pool.game_id).game_name %></td>
        <td><%= Match.find(pool.match_id).match_no %></td>
        <td><%= pool.create_time.strftime("%Y年%m月%d日 %H:%M:%S") %></td>
        <td><%= pool.sell_status %></td>
        <td><%= pool.match_result %></td>
        <td><%= link_to '查看', pool %></td>
        <td><%= link_to '编辑', edit_pool_path(pool) %></td>
        <td><%= link_to '删除', pool, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新加奖池', new_pool_path %>

app/views/pools/new.html.erb
<h1>新加奖池</h1>

<%= render 'form' %>

<%= link_to '返回', pools_path %>

app/views/pools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>游戏:</strong>
  <%= @pool.game_id %>
</p>

<p>
  <strong>赛事:</strong>
  <%= @pool.match_id %>
</p>

<p>
  <strong>创建时间:</strong>
  <%= @pool.create_time.strftime('%Y年%m月%d日%H:%M:%S') %>
</p>

<p>
  <strong>销售状态:</strong>
  <%= @pool.sell_status %>
</p>

<p>
  <strong>赛果:</strong>
  <%= @pool.match_result %>
</p>

<%= link_to '编辑', edit_pool_path(@pool) %> |
<%= link_to '返回', pools_path %>