config/routes.rb
Ilbdmt::Application.routes.draw do
  resources :catalogs

  resources :users
	
	resources :sessions, only: [:new, :create, :destroy]

	resources :areas

  resources :activities

  get "sell_tickets/home"
  
	resources :pools

  resources :games

  resources :matches

	root to: 'static_pages#home'
	match '/signup/', to: 'users#new',						via: 'get'
	match '/signin/', to: 'sessions#new',					via: 'get'
	match '/signout/',to: 'sessions#destroy',			via: 'delete'
	match '/help',		to: 'static_pages#help',		via: 'get'
	match '/about',		to: 'static_pages#about',		via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

	match '/sell',			to: 'sell_tickets#home',	via: 'get'
	match '/game',			to: 'sell_tickets#game',	via: 'get'
	match '/score',			to: 'sell_tickets#score',	via: 'get'
	match '/total',			to: 'sell_tickets#total',	via: 'get'
	match '/hfad',			to: 'sell_tickets#hfad',	via: 'get'

	match '/badminton',	to: 'activities#badminton',	via: 'get'
	match '/skiing',	to: 'activities#skiing',	via: 'get'

end

app/models/match.rb
class Match < ActiveRecord::Base
	has_many :pools
	has_many :games, through: :pools
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
	before_action :set_match, only: [:show, :edit, :update, :destroy]

  # GET /matches
  # GET /matches.json
  def index
    @matches = Match.all
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
  end

  # GET /matches/new
  def new
    @match = Match.new
  end

  # GET /matches/1/edit
  def edit
  end

  # POST /matches
  # POST /matches.json
  def create
    @match = Match.new(match_params)

    respond_to do |format|
      if @match.save
        format.html { redirect_to @match, notice: '赛事创建成功.' }
        format.json { render action: 'show', status: :created, location: @match }
      else
        format.html { render action: 'new' }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1
  # PATCH/PUT /matches/1.json
  def update
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to @match, notice: 'Match was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match.destroy
    respond_to do |format|
      format.html { redirect_to matches_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def match_params
      params.require(:match).permit(:match_no, :player_a, :player_b, :start_time, :end_time, :operator)
    end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_form.html.erb
<%= form_for(@match) do |f| %>
  <% if @match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
      <% @match.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :'赛事编号' %><br>
    <%= f.text_field :match_no %>
  </div>
  <div class="field">
    <%= f.label :'选手A' %><br>
    <%= f.text_field :player_a %>
  </div>
  <div class="field">
    <%= f.label :'选手B' %><br>
    <%= f.text_field :player_b %>
  </div>
  <div class="field">
    <%= f.label :'开始时间' %><br>
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :'结束时间' %><br>
    <%= f.datetime_select :end_time %>
  </div>
  <div class="field">
    <%= f.label :'管理员编号' %><br>
    <%= f.number_field :operator %>
  </div>
  <div class="actions">
    <%= f.submit '提交' %>
  </div>
<% end %>

app/views/matches/edit.html.erb
<h1>赛事修改</h1>

<%= render 'form' %>

<%= link_to '查看', @match %> |
<%= link_to '返回', matches_path %>

app/views/matches/index.html.erb
<h1>赛事信息</h1>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>赛事编号</th>
      <th>选手A</th>
      <th>选手B</th>
      <th>开始时间</th>
      <th>结束时间</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @matches.each do |match| %>
      <tr>
        <td><%= match.match_no %></td>
        <td><%= match.player_a %></td>
        <td><%= match.player_b %></td>
        <td><%= match.start_time.strftime("%Y年%m月%d日%H时%M分") %></td>
        <td><%= match.end_time.strftime("%Y年%m月%d日%H时%M分") %></td>
        <td><%= link_to '查看', match %></td>
        <td><%= link_to '修改', edit_match_path(match) %></td>
        <td><%= link_to '删除', match, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新加赛事', new_match_path %>

app/views/matches/new.html.erb
<h1>新建赛事</h1>

<%= render 'form' %>

<%= link_to '返回', matches_path %>

app/views/matches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>赛事id:</strong>
  <%= @match.id %>
</p>
<p>
  <strong>赛事编号:</strong>
  <%= @match.match_no %>
</p>

<p>
  <strong>选手A:</strong>
  <%= @match.player_a %>
</p>

<p>
  <strong>选手B:</strong>
  <%= @match.player_b %>
</p>

<p>
  <strong>开始时间:</strong>
  <%= @match.start_time.strftime("%y年%m月%d日 %H时%M分") %>
</p>

<p>
  <strong>结束时间:</strong>
  <%= @match.end_time.strftime("%y年%m月%d日 %H时%M分") %>
</p>

<p>
  <strong>管理员:</strong>
  <%= @match.operator %>
</p>

<%= link_to '修改', edit_match_path(@match) %> |
<%= link_to '返回', matches_path %>