config/routes.rb
Ilbdmt::Application.routes.draw do
  resources :catalogs

  resources :users
	
	resources :sessions, only: [:new, :create, :destroy]

	resources :areas

  resources :activities

  get "sell_tickets/home"
  
	resources :pools

  resources :games

  resources :matches

	root to: 'static_pages#home'
	match '/signup/', to: 'users#new',						via: 'get'
	match '/signin/', to: 'sessions#new',					via: 'get'
	match '/signout/',to: 'sessions#destroy',			via: 'delete'
	match '/help',		to: 'static_pages#help',		via: 'get'
	match '/about',		to: 'static_pages#about',		via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

	match '/sell',			to: 'sell_tickets#home',	via: 'get'
	match '/game',			to: 'sell_tickets#game',	via: 'get'
	match '/score',			to: 'sell_tickets#score',	via: 'get'
	match '/total',			to: 'sell_tickets#total',	via: 'get'
	match '/hfad',			to: 'sell_tickets#hfad',	via: 'get'

	match '/badminton',	to: 'activities#badminton',	via: 'get'
	match '/skiing',	to: 'activities#skiing',	via: 'get'

end

app/models/activity.rb
class Activity < ActiveRecord::Base
	belongs_to :catalog
end

app/models/area.rb
class Area < ActiveRecord::Base
end

app/models/catalog.rb
class Catalog < ActiveRecord::Base
	has_many :activities
end

app/models/game.rb
class Game < ActiveRecord::Base
	has_many :pools
	has_many :matches, through: :appointments
end

app/models/match.rb
class Match < ActiveRecord::Base
	has_many :pools
	has_many :games, through: :pools
end

app/models/pool.rb
class Pool < ActiveRecord::Base
	belongs_to :game
	belongs_to :match
end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { self.email = email.downcase }
	before_create :create_remember_token

	validates :name, presence: true, length: { maximum: 50}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, 
										format: { with: VALID_EMAIL_REGEX },
										uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, length: { minimum: 6 }

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.encrypt(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private
		def create_remember_token
			self.remember_token = User.encrypt(User.new_remember_token)
		end
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :set_area, only: [:show, :edit, :update, :destroy]

  # GET /areas
  # GET /areas.json
  def index
    @areas = Area.all
  end

  # GET /areas/1
  # GET /areas/1.json
  def show
  end

  # GET /areas/new
  def new
    @area = Area.new
  end

  # GET /areas/1/edit
  def edit
  end

  # POST /areas
  # POST /areas.json
  def create
    @area = Area.new(area_params)

    respond_to do |format|
      if @area.save
        format.html { redirect_to @area, notice: 'Area was successfully created.' }
        format.json { render action: 'show', status: :created, location: @area }
      else
        format.html { render action: 'new' }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /areas/1
  # PATCH/PUT /areas/1.json
  def update
    respond_to do |format|
      if @area.update(area_params)
        format.html { redirect_to @area, notice: 'Area was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /areas/1
  # DELETE /areas/1.json
  def destroy
    @area.destroy
    respond_to do |format|
      format.html { redirect_to areas_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_area
      @area = Area.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def area_params
      params.require(:area).permit(:id, :title, :pid)
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
	before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: '游戏创建成功.' }
        format.json { render action: 'show', status: :created, location: @game }
      else
        format.html { render action: 'new' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:game_no, :game_name)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/catalogs_helper.rb
module CatalogsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/pools_helper.rb
module PoolsHelper
end

app/helpers/sell_tickets_helper.rb
module SellTicketsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
		remember_token = User.new_remember_token
		cookies.permanent[:remember_token] = remember_token
		user.update_attribute(:remember_token, User.encrypt(remember_token))
		self.current_user = user
	end
	
	def signed_in?
		!current_user.nil?
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		remember_token = User.encrypt(cookies[:remember_token])
		@current_user ||= User.find_by(remember_token: remember_token)
	end

	def current_user?(user)
		user == current_user
	end

	def sign_out
		self.current_user = nil
		cookies.delete(:remember_token)
	end

	def redirect_back_or(default)
		redirect_to(session[:return_to] || default)
		session.delete(:return_to)
	end

	def store_location
		session[:return_to] = request.fullpath if request.get?
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user, options = { size: 50 } )
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
<small>
<a href="http://ilbdmt.cn">我爱竞猜</a>
by Tharvest
</small>
<nav>
<ul>
<li><%= link_to "关于我们", about_path %></li>
<li><%= link_to "联系我们", contact_path %></li>
<li><%= link_to "新闻媒体", '#' %></li>
</ul>
</nav>
</footer>

app/views/layouts/_header.html.erb
	<header class="navbar navbar-fixed-top navbar-inverse">
		<div class="navbar-inner">
			<div class="container">
				<%= link_to "我爱竞猜", root_path, id: "logo" %>
				<nav>
					<ul class="nav pull-right">
						<li><%= link_to "主页",		root_path %></li>
						<li><%= link_to "帮助",		help_path %></li>
						<% if signed_in? %>
							<li><%= link_to "我要购彩",	sell_path %></li>
							<li><%= link_to "赛事管理",	matches_path %></li>
							<li><%= link_to "游戏管理",	games_path %></li>
							<li><%= link_to "奖池管理",	pools_path %></li>
							<li><%= link_to "用户", users_path %></li>
							<li id="fat-menu" class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown">
									<!--%= current_user.name %-->账户<b class="caret"></b>
								</a>
								<ul class="dropdown-menu">
									<li><%= link_to "Profile", current_user %></li>
									<li><%= link_to "设置", edit_user_path(current_user) %></li>
									<li class="driver"></li>
									<li>
										<%= link_to "Sign out", signout_path, method: "delete" %>
									</li>
								</ul>
							</li>
						<% else %>
							<li><%= link_to "登录", signin_path %></li>
						<% end %>
					</ul>
				</nav>
			</div>
		</div>
	</header>

app/views/layouts/_left.html.erb
<div class="span2">
	<div class="well sidebar-nav">
		<ul class="nav nav-list">
			<li class="nav-header">活动</li>
			<%#= render 'catalogs/list' %>
			<li><%= link_to "羽毛球", badminton_path %></li>
			<!--li><%= link_to "篮球", '#' %></li>
			<li><%= link_to "足球", '#' %></li>
			<li><%= link_to "乒乓球", '#' %></li>
			<li><%= link_to "排球", '#' %></li>
			<li><%= link_to "滑冰", '#' %></li-->
			<li><%= link_to "滑雪", skiing_path %></li>
			<!--li><%= link_to "K歌", '#' %></li>
			<li><%= link_to "跳舞", '#'  %></li>
			<li><%= link_to "游泳", '#' %></li-->
		</ul>
	</div><!--/.well -->
</div><!--/span-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>爱运动!爱生活!| <%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
	<script src="//tinymce.cachefly.net/4.0/tinymce.min.js"></script>
	<script>
		tinymce.init({selector:'textarea'});
	</script>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<div class="row">
			<%= render 'layouts/left' %>
			<div class="span9">
				<% flash.each do |key, value| %>
					<div class="alert alert-<%= key %>"><%= value %></div>
				<% end %>
				<%= yield %>
			</div>
		</div>
		<%= render 'layouts/footer' %>
		<%= debug(params) if Rails.env.development? %>
	</div>
</body>
</html>

app/views/layouts/static_pages.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>爱运动!爱生活!| <%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |key, value| %>
			<div class="alert alert-<%= key %>"><%= value %></div>
		<% end %>
		<%= yield %>
		<%= render 'layouts/footer' %>
		<%= debug(params) if Rails.env.development? %>
	</div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			The form contains <%= pluralize(@user.errors.count, "error") %>
		</div>
		<ul>
		<% @user.errors.full_messages.each do |msg| %>
		<li>* <%= msg %></li>
		<% end %>
		</ul>
	</div>
<% end %>